# Generated by Django 5.0.3 on 2024-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='client_images/'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
